$primary = rgb(6f4e63)
$surface = rgb(f7e6ee)
$secondary = rgb(f2c1d4)
$error = rgb(e6687c)
$tertiary = rgb(8f6a7c)
$surface_lowest = rgb(f7e7ef)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
