# name: Everviolet Spring
# author: linnie
# comfy colorscheme for cozy morning vibes
$base		= 0xff2B3538
$mantle		= 0xff232A2E
$crust		= 0xff1C2225
$surface1	= 0xff313B40
$surface2	= 0xff4A585C
$surface0	= 0xff313B40
$overlay0	= 0xff58686D
$overlay1	= 0xff6F8788
$overlay2	= 0xff839E9A
$subtext0	= 0xff96B4AA
$subtext1	= 0xffADC9BC
$text		= 0xffF8F9E8
$cherry		= 0xffF6CEE5
$pink		= 0xffF3C0E5
$purple		= 0xffD0BBF0
$blue		= 0xffB2CFED
$snow		= 0xffAFDFE6
$skye		= 0xffACE0D4
$aqua		= 0xffADDEB9
$green		= 0xffCAE0A7
$lime		= 0xffDBE6AF
$yellow		= 0xffF5D098
$orange		= 0xffF7A182
$red		= 0xffF57F82
