# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = PF Din Text Universal Medium

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/.config/hypr/hyprlock-images/hyprlock-elysia.png
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(31, 29, 46, 0.5)

    outer_color = rgba(ebbcbaee) rgba(c4a7e7ee) 45deg
    check_color = rgba(26233aee) rgba(6e6a86ee) 120deg
    fail_color = rgba(eb6f92ee) rgba(b4637aee) 40deg

    font_color = rgb(196, 167, 231)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = you'll get there. just take it slow, please.
    fail_text = try again, i know that keyboard sucks

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = -500, -60
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12 # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    color = rgb(196, 167, 231)
    font_family = $font

    position = -500, -70
    halign = center
    valign = top

    shadow_passes = 4
    shadow_size = 6
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    color = rgb(235, 188, 186)
    font_size = 25
    font_family = $font

    position = -500, -180
    halign = center
    valign = top

    shadow_passes = 4
    shadow_size = 6
}

# KEYBOARD LAYOUT
# label {
   #  monitor =
   #  text = $LAYOUT[en,ru]
   #  font_size = 24
   #  onclick = hyprctl switchxkblayout all next

   #  position = 250, -20
   #  halign = center
   #  valign = center
# }

# USERNAME
label {
	monitor =
	text = $DESC
	color = rgba(156, 207, 216, 1.0)
	font_family = $font
	font_size = 45
	position = -500, 50

	shadow_passes = 4
	shadow_size = 6
}

# motivational text
label {
	monitor =
	text = you'll be okay. you can't give up, no matter what.
	font_family = $font
	font_size = 25
	position = 0, 40
	halign = center
	valign = bottom
	color = rgb(246, 193, 119)
	shadow_size = 3
	shadow_passes = 2
}

# IMAGE OF YOUR CHOOSING
image {
	path = ~/.config/hypr/hyprlock-images/cyrene.png
	border_size = 4
	border_color = rgb(156, 207, 216)
	position = -500, 180
	shadow_passes = 7
	shadow_size = 3
}
