# set wallpapers
# wallpaper = HDMI-A-1, ~/.config/wallpaper/MiyabiWallpaperFeet.png
# wallpaper = DP-1, ~/.config/wallpaper/VivianWallpaper.png
# wallpaper = DP-1, ~/.config/wallpaper/hyprwall-elysia.png
# wallpaper = HDMI-A-1, ~/.config/wallpaper/hyprwall-elysia-2.png
# wallpaper = DP-1, ~/.config/wallpaper/hyprwall-yuzuali.png
# wallpaper = HDMI-A-1, ~/.config/wallpaper/hyprwall-elysia-3.png
#wallpaper {
#	monitor = HDMI-A-1
#	path = ~/.config/wallpaper/shirashi-an-hyprwall.png
#}
# wallpaper { 
#	monitor = DP-1
#	path = ~/.config/wallpaper/hyprwall-nene.png
#}
#wallpaper {
#	monitor = DP-1
#	path = ~/.config/wallpaper/hyprwall-emunene.png
#}
#wallpaper {
#	monitor = DP-1
#	path = ~/.config/wallpaper/A_Dream_On_A_Melody_T.png
#}

#wallpaper {
#	monitor = HDMI-A-1
#	path = ~/.config/wallpaper/Gotta_Be_An_English_Master!_T.png
#}
splash=false
